name: Validating YAML file configuration
on: [pull_request]
jobs:
  validate-config:
    runs-on: ubuntu-latest
    steps:
      - name: Install openapi-generator-cli
        run: npm install -g @openapitools/openapi-generator-cli
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Validate llamacpp.yml
        run: openapi-generator-cli validate -i $GITHUB_WORKSPACE/models/llamacpp.yml